In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train=pd.read_csv("store_sales_train.csv")
df_test=pd.read_csv("store_sales_test.csv")

In [3]:
df_train

id        date  store_nbr                      family     sales  \
0              0  2013-01-01          1                  AUTOMOTIVE     0.000   
1              1  2013-01-01          1                   BABY CARE     0.000   
2              2  2013-01-01          1                      BEAUTY     0.000   
3              3  2013-01-01          1                   BEVERAGES     0.000   
4              4  2013-01-01          1                       BOOKS     0.000   
...          ...         ...        ...                         ...       ...   
3000883  3000883  2017-08-15          9                     POULTRY   438.133   
3000884  3000884  2017-08-15          9              PREPARED FOODS   154.553   
3000885  3000885  2017-08-15          9                     PRODUCE  2419.729   
3000886  3000886  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000   
3000887  3000887  2017-08-15          9                     SEAFOOD    16.000   

         onpromotion  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
3000883            0  
3000884            1  
3000885          148  
3000886            8  
3000887            0  

[3000888 rows x 6 columns]

In [4]:
df_holiday=pd.read_csv("holidays_events.csv")

In [5]:
df_holiday

date        type    locale locale_name  \
0    2012-03-02     Holiday     Local       Manta   
1    2012-04-01     Holiday  Regional    Cotopaxi   
2    2012-04-12     Holiday     Local      Cuenca   
3    2012-04-14     Holiday     Local    Libertad   
4    2012-04-21     Holiday     Local    Riobamba   
..          ...         ...       ...         ...   
345  2017-12-22  Additional  National     Ecuador   
346  2017-12-23  Additional  National     Ecuador   
347  2017-12-24  Additional  National     Ecuador   
348  2017-12-25     Holiday  National     Ecuador   
349  2017-12-26  Additional  National     Ecuador   

                       description  transferred  
0               Fundacion de Manta        False  
1    Provincializacion de Cotopaxi        False  
2              Fundacion de Cuenca        False  
3        Cantonizacion de Libertad        False  
4        Cantonizacion de Riobamba        False  
..                             ...          ...  
345                      Navidad-3        False  
346                      Navidad-2        False  
347                      Navidad-1        False  
348                        Navidad        False  
349                      Navidad+1        False  

[350 rows x 6 columns]

In [6]:
df_oil=pd.read_csv("oil.csv")

In [7]:
df_oil

date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [8]:
df_stores=pd.read_csv("stores.csv")

In [9]:
df_transactions=pd.read_csv("transactions.csv")

In [10]:
df_holiday.isna().sum()

date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [11]:
df_oil.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [12]:
df_oil

date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [13]:
df_oil.dropna()

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [14]:
df_stores.isna().sum()

store_nbr    0
city         0
state        0
type         0
cluster      0
dtype: int64

In [15]:
df_transactions.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [16]:
df_holiday ['date'] = pd.to_datetime(df_holiday['date']) 
df_oil ['date'] = pd.to_datetime(df_oil ['date'])
df_transactions ['date'] = pd.to_datetime(df_transactions ['date']) 

In [17]:
df_train

id        date  store_nbr                      family     sales  \
0              0  2013-01-01          1                  AUTOMOTIVE     0.000   
1              1  2013-01-01          1                   BABY CARE     0.000   
2              2  2013-01-01          1                      BEAUTY     0.000   
3              3  2013-01-01          1                   BEVERAGES     0.000   
4              4  2013-01-01          1                       BOOKS     0.000   
...          ...         ...        ...                         ...       ...   
3000883  3000883  2017-08-15          9                     POULTRY   438.133   
3000884  3000884  2017-08-15          9              PREPARED FOODS   154.553   
3000885  3000885  2017-08-15          9                     PRODUCE  2419.729   
3000886  3000886  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000   
3000887  3000887  2017-08-15          9                     SEAFOOD    16.000   

         onpromotion  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
3000883            0  
3000884            1  
3000885          148  
3000886            8  
3000887            0  

[3000888 rows x 6 columns]

In [18]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype  
---  ------       -----  
 0   id           int64  
 1   date         object 
 2   store_nbr    int64  
 3   family       object 
 4   sales        float64
 5   onpromotion  int64  
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB


In [19]:
df_train.isna().sum()

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

In [20]:
df_train.date.unique()

array(['2013-01-01', '2013-01-02', '2013-01-03', ..., '2017-08-13',
       '2017-08-14', '2017-08-15'], dtype=object)

In [21]:
df_train.store_nbr.unique()

array([ 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  2, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29,  3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,  4,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  5, 50, 51, 52, 53, 54,  6,
        7,  8,  9], dtype=int64)

In [22]:
df_train.family.unique()

array(['AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES', 'BOOKS',
       'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY', 'DELI', 'EGGS',
       'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD'], dtype=object)

In [23]:
df_train.sales.unique()

array([0.000000e+00, 2.000000e+00, 8.100000e+02, ..., 4.381330e+02,
       1.545530e+02, 2.419729e+03])

In [24]:
df_train.onpromotion.unique()

array([  0,   3,   5,   1,  56,  20,  19,   2,   4,  18,  17,  12,   6,
         7,  10,   9,  50,   8,  16,  42,  51,  13,  15,  47,  21,  40,
        37,  54,  24,  58,  22,  59,  11,  45,  25,  55,  26,  43,  35,
        14,  28,  46,  36,  32,  53,  57,  27,  39,  41,  30,  29,  49,
        23,  48,  44,  38,  31,  52,  33,  34,  61,  60, 116,  86,  73,
       113, 102,  68, 104,  93,  70,  92, 121,  72, 178, 174, 161, 118,
       105, 172, 163, 167, 142, 154, 133, 180, 181, 173, 165, 168, 186,
       140, 149, 145, 169, 188,  62,  84, 111,  65, 107,  63, 101,  87,
       125,  94, 114, 171, 153, 170, 166, 141, 155, 179, 192, 131, 147,
       151, 189,  79,  74, 110,  64,  67,  99, 123, 157, 117, 150, 182,
       162, 160, 194, 135, 190,  69, 108,  89, 126, 156, 103, 146, 132,
       177, 164, 176, 112,  75, 109,  91, 128, 175, 187, 148, 137, 184,
       196, 144, 158, 119, 106,  66, 100,  90, 120, 115,  98, 159, 152,
       185, 139, 143,  80, 124,  71, 134, 193,  78,  88, 122, 13

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le=LabelEncoder()

In [27]:
features_to_change=['date','family']

In [28]:
for i in features_to_change:
    df_test[i]=le.fit_transform(df_test[i])

In [29]:
for i in features_to_change:
    df_train[i]=le.fit_transform(df_train[i])

In [30]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype  
---  ------       -----  
 0   id           int64  
 1   date         int32  
 2   store_nbr    int64  
 3   family       int32  
 4   sales        float64
 5   onpromotion  int64  
dtypes: float64(1), int32(2), int64(3)
memory usage: 114.5 MB


In [31]:
df_train.corr()

id          date     store_nbr        family     sales  \
id           1.000000  9.999998e-01  3.013308e-04  1.099169e-05  0.085784   
date         1.000000  1.000000e+00 -2.371683e-16  2.448464e-14  0.085733   
store_nbr    0.000301 -2.371683e-16  1.000000e+00  4.323589e-18  0.041196   
family       0.000011  2.448464e-14  4.323589e-18  1.000000e+00 -0.114159   
sales        0.085784  8.573309e-02  4.119605e-02 -1.141591e-01  1.000000   
onpromotion  0.206260  2.062492e-01  7.285647e-03 -4.585474e-02  0.427923   

             onpromotion  
id              0.206260  
date            0.206249  
store_nbr       0.007286  
family         -0.045855  
sales           0.427923  
onpromotion     1.000000

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
model=LinearRegression()

In [34]:
Y_train=df_train.sales

In [35]:
X_train=df_train.drop("sales",axis=1)

In [36]:
model.fit(X_train,Y_train)

LinearRegression()

In [37]:
df_test

id  date  store_nbr  family  onpromotion
0      3000888     0          1       0            0
1      3000889     0          1       1            0
2      3000890     0          1       2            2
3      3000891     0          1       3           20
4      3000892     0          1       4            0
...        ...   ...        ...     ...          ...
28507  3029395    15          9      28            1
28508  3029396    15          9      29            0
28509  3029397    15          9      30            1
28510  3029398    15          9      31            9
28511  3029399    15          9      32            0

[28512 rows x 5 columns]

In [38]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  int32
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  int32
 4   onpromotion  28512 non-null  int64
dtypes: int32(2), int64(3)
memory usage: 891.1 KB


In [39]:
y_pred=model.predict(df_test)

In [40]:
submission_Linear = pd.DataFrame({'id': df_test.id, 'sales': y_pred})
submission_Linear.to_csv('submission_Linear.csv', index=False)

In [41]:
df_train

id  date  store_nbr  family     sales  onpromotion
0              0     0          1       0     0.000            0
1              1     0          1       1     0.000            0
2              2     0          1       2     0.000            0
3              3     0          1       3     0.000            0
4              4     0          1       4     0.000            0
...          ...   ...        ...     ...       ...          ...
3000883  3000883  1683          9      28   438.133            0
3000884  3000884  1683          9      29   154.553            1
3000885  3000885  1683          9      30  2419.729          148
3000886  3000886  1683          9      31   121.000            8
3000887  3000887  1683          9      32    16.000            0

[3000888 rows x 6 columns]

In [42]:
df_test

id  date  store_nbr  family  onpromotion
0      3000888     0          1       0            0
1      3000889     0          1       1            0
2      3000890     0          1       2            2
3      3000891     0          1       3           20
4      3000892     0          1       4            0
...        ...   ...        ...     ...          ...
28507  3029395    15          9      28            1
28508  3029396    15          9      29            0
28509  3029397    15          9      30            1
28510  3029398    15          9      31            9
28511  3029399    15          9      32            0

[28512 rows x 5 columns]